language: node_js

node_js:
- "4"

env:
  global:
    - CXX=g++-4.8
    - PATH=$PATH:$HOME/gcloud/google-cloud-sdk/bin
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/test/encrypted/client-secret.json
    - GCLOUD_PROJECT=mxfactorial

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

cache:
  directories:
  - node_modules

script:
  - npm run test
  - npm run lint

after_script: "cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
